import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  card: {
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
    background: "#161b22",
    border: "1px solid #30363d",
    borderRadius: 10,
    padding: 20,
    color: "#e6edf3",
    width: 440,
  },
  title: {
    margin: "0 0 16px 0",
    fontSize: 16,
    fontWeight: 700,
  },
  tabs: {
    display: "flex",
    gap: 6,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  tab: {
    background: "transparent",
    border: "1px solid #30363d",
    color: "#8b949e",
    borderRadius: 6,
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  tabActive: {
    border: "1px solid #58a6ff",
    color: "#58a6ff",
  },
  dropZone: {
    border: "1px dashed #30363d",
    borderRadius: 8,
    padding: "24px 16px",
    textAlign: "center",
    cursor: "pointer",
    background: "#0d1117",
  },
  dropZoneActive: {
    border: "1px dashed #58a6ff",
    background: "#0d1117",
  },
  dropZoneText: {
    fontSize: 12,
    color: "#8b949e",
    margin: 0,
  },
  fileList: {
    listStyle: "none",
    margin: "12px 0",
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    maxHeight: 160,
    overflowY: "auto",
  },
  fileItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: "#0d1117",
    border: "1px solid #21262d",
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: 12,
    gap: 8,
  },
  fileName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  removeButton: {
    background: "transparent",
    border: "none",
    color: "#6e7681",
    fontSize: 16,
    lineHeight: 1,
    cursor: "pointer",
    padding: "0 4px",
    flexShrink: 0,
  },
  primaryButton: {
    background: "#1f6feb",
    border: "none",
    borderRadius: 6,
    padding: "8px 16px",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  primaryButtonDisabled: {
    background: "#21262d",
    color: "#6e7681",
    cursor: "not-allowed",
  },
  hint: {
    fontSize: 11,
    color: "#6e7681",
    margin: "10px 0 0 0",
  },
  error: {
    fontSize: 12,
    color: "#f85149",
    margin: "10px 0 0 0",
  },
  success: {
    fontSize: 12,
    color: "#3fb950",
    margin: "10px 0 0 0",
  },
  footer: {
    marginTop: 16,
    fontSize: 11,
    color: "#6e7681",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
};
