import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  card: {
    fontFamily:
      "'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    background: "#0f1512",
    border: "1px solid #2c3d33",
    borderRadius: 3,
    padding: 20,
    color: "#e7f2ec",
    width: 440,
  },
  title: {
    margin: "0 0 16px 0",
    fontSize: 16,
    fontWeight: 700,
  },
  tabs: {
    display: "flex",
    gap: 6,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  tab: {
    background: "transparent",
    border: "1px solid #2c3d33",
    color: "#839a8d",
    borderRadius: 2,
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  tabActive: {
    border: "1px solid #2dd4bf",
    color: "#2dd4bf",
  },
  dropZone: {
    border: "1px dashed #2c3d33",
    borderRadius: 2,
    padding: "24px 16px",
    textAlign: "center",
    cursor: "pointer",
    background: "#080b09",
  },
  dropZoneActive: {
    border: "1px dashed #2dd4bf",
    background: "#080b09",
  },
  dropZoneText: {
    fontSize: 12,
    color: "#839a8d",
    margin: 0,
  },
  fileList: {
    listStyle: "none",
    margin: "12px 0",
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    maxHeight: 160,
    overflowY: "auto",
  },
  fileItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: "#080b09",
    border: "1px solid #1e2b23",
    borderRadius: 2,
    padding: "6px 10px",
    fontSize: 12,
    gap: 8,
  },
  fileName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  removeButton: {
    background: "transparent",
    border: "none",
    color: "#55685d",
    fontSize: 16,
    lineHeight: 1,
    cursor: "pointer",
    padding: "0 4px",
    flexShrink: 0,
  },
  primaryButton: {
    background: "#0f766e",
    border: "none",
    borderRadius: 2,
    padding: "8px 16px",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  primaryButtonDisabled: {
    background: "#1e2b23",
    color: "#55685d",
    cursor: "not-allowed",
  },
  hint: {
    fontSize: 11,
    color: "#55685d",
    margin: "10px 0 0 0",
  },
  error: {
    fontSize: 12,
    color: "#ff6b6b",
    margin: "10px 0 0 0",
  },
  success: {
    fontSize: 12,
    color: "#3fb950",
    margin: "10px 0 0 0",
  },
  footer: {
    marginTop: 16,
    fontSize: 11,
    color: "#55685d",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
};
