import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  card: {
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
    background: "#161b22",
    border: "1px solid #30363d",
    borderRadius: 10,
    padding: 20,
    color: "#e6edf3",
    width: 460,
  },
  title: {
    margin: "0 0 16px 0",
    fontSize: 16,
    fontWeight: 700,
  },
  dropZone: {
    border: "1px dashed #30363d",
    borderRadius: 8,
    padding: "24px 16px",
    textAlign: "center",
    cursor: "pointer",
    background: "#0d1117",
  },
  dropZoneActive: {
    border: "1px dashed #58a6ff",
    background: "#0d1117",
  },
  dropZoneText: {
    fontSize: 12,
    color: "#8b949e",
    margin: 0,
  },
  preview: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#0d1117",
    border: "1px solid #21262d",
    borderRadius: 6,
    padding: "8px 10px",
    margin: "12px 0",
  },
  previewImage: {
    maxWidth: 64,
    maxHeight: 64,
    borderRadius: 4,
  },
  previewInfo: {
    fontSize: 12,
    color: "#8b949e",
  },
  progressWrap: {
    margin: "14px 0",
  },
  progressLabel: {
    fontSize: 12,
    color: "#8b949e",
    marginBottom: 6,
  },
  progressTrack: {
    background: "#0d1117",
    border: "1px solid #21262d",
    borderRadius: 4,
    height: 8,
    overflow: "hidden",
  },
  progressFill: {
    background: "#58a6ff",
    height: "100%",
    borderRadius: 4,
    transition: "width 0.15s ease",
  },
  textarea: {
    width: "100%",
    minHeight: 200,
    resize: "vertical",
    background: "#0d1117",
    border: "1px solid #30363d",
    borderRadius: 6,
    padding: "10px 12px",
    color: "#e6edf3",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
    fontSize: 12,
    lineHeight: 1.5,
    boxSizing: "border-box",
  },
  row: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    margin: "12px 0",
    flexWrap: "wrap",
  },
  primaryButton: {
    background: "#1f6feb",
    border: "none",
    borderRadius: 6,
    padding: "8px 16px",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  primaryButtonDisabled: {
    background: "#21262d",
    color: "#6e7681",
    cursor: "not-allowed",
  },
  secondaryButton: {
    background: "transparent",
    border: "1px solid #30363d",
    borderRadius: 6,
    padding: "7px 14px",
    color: "#8b949e",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  hint: {
    fontSize: 11,
    color: "#6e7681",
    margin: "10px 0 0 0",
  },
  error: {
    fontSize: 12,
    color: "#f85149",
    margin: "10px 0 0 0",
  },
  footer: {
    marginTop: 16,
    fontSize: 11,
    color: "#6e7681",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
};
