import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  card: {
    fontFamily:
      "'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    background: "#0f1512",
    border: "1px solid #2c3d33",
    borderRadius: 3,
    padding: 20,
    color: "#e7f2ec",
    width: 460,
  },
  title: {
    margin: "0 0 16px 0",
    fontSize: 16,
    fontWeight: 700,
  },
  dropZone: {
    border: "1px dashed #2c3d33",
    borderRadius: 2,
    padding: "24px 16px",
    textAlign: "center",
    cursor: "pointer",
    background: "#080b09",
  },
  dropZoneActive: {
    border: "1px dashed #2dd4bf",
    background: "#080b09",
  },
  dropZoneText: {
    fontSize: 12,
    color: "#839a8d",
    margin: 0,
  },
  preview: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#080b09",
    border: "1px solid #1e2b23",
    borderRadius: 2,
    padding: "8px 10px",
    margin: "12px 0",
  },
  previewImage: {
    maxWidth: 64,
    maxHeight: 64,
    borderRadius: 2,
  },
  previewInfo: {
    fontSize: 12,
    color: "#839a8d",
  },
  progressWrap: {
    margin: "14px 0",
  },
  progressLabel: {
    fontSize: 12,
    color: "#839a8d",
    marginBottom: 6,
  },
  progressTrack: {
    background: "#080b09",
    border: "1px solid #1e2b23",
    borderRadius: 2,
    height: 8,
    overflow: "hidden",
  },
  progressFill: {
    background: "#2dd4bf",
    height: "100%",
    borderRadius: 2,
    transition: "width 0.15s ease",
  },
  textarea: {
    width: "100%",
    minHeight: 200,
    resize: "vertical",
    background: "#080b09",
    border: "1px solid #2c3d33",
    borderRadius: 2,
    padding: "10px 12px",
    color: "#e7f2ec",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
    fontSize: 12,
    lineHeight: 1.5,
    boxSizing: "border-box",
  },
  row: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    margin: "12px 0",
    flexWrap: "wrap",
  },
  primaryButton: {
    background: "#0f766e",
    border: "none",
    borderRadius: 2,
    padding: "8px 16px",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  primaryButtonDisabled: {
    background: "#1e2b23",
    color: "#55685d",
    cursor: "not-allowed",
  },
  secondaryButton: {
    background: "transparent",
    border: "1px solid #2c3d33",
    borderRadius: 2,
    padding: "7px 14px",
    color: "#839a8d",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  hint: {
    fontSize: 11,
    color: "#55685d",
    margin: "10px 0 0 0",
  },
  error: {
    fontSize: 12,
    color: "#ff6b6b",
    margin: "10px 0 0 0",
  },
  footer: {
    marginTop: 16,
    fontSize: 11,
    color: "#55685d",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
};
