import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  card: {
    fontFamily:
      "'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    background: "#0f1512",
    border: "1px solid #2c3d33",
    borderRadius: 3,
    padding: 20,
    color: "#e7f2ec",
    width: 440,
  },
  title: {
    margin: "0 0 16px 0",
    fontSize: 16,
    fontWeight: 700,
  },
  dropZone: {
    border: "1px dashed #2c3d33",
    borderRadius: 2,
    padding: "24px 16px",
    textAlign: "center",
    cursor: "pointer",
    background: "#080b09",
  },
  dropZoneActive: {
    border: "1px dashed #2dd4bf",
    background: "#080b09",
  },
  dropZoneText: {
    fontSize: 12,
    color: "#839a8d",
    margin: 0,
  },
  toolbar: {
    display: "flex",
    gap: 6,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  toolButton: {
    background: "transparent",
    border: "1px solid #2c3d33",
    color: "#839a8d",
    borderRadius: 2,
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  toolButtonActive: {
    border: "1px solid #2dd4bf",
    color: "#2dd4bf",
    background: "rgba(45, 212, 191, 0.1)",
  },
  toolButtonDanger: {
    color: "#ff6b6b",
  },
  pageNav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    fontSize: 12,
    color: "#839a8d",
  },
  navButton: {
    background: "#080b09",
    border: "1px solid #2c3d33",
    color: "#e7f2ec",
    borderRadius: 2,
    padding: "3px 10px",
    fontSize: 12,
    cursor: "pointer",
  },
  navButtonDisabled: {
    color: "#484f58",
    cursor: "not-allowed",
  },
  canvasWrap: {
    position: "relative",
    background: "#fff",
    borderRadius: 2,
    overflow: "hidden",
    margin: "0 auto",
    lineHeight: 0,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  textAnnotation: {
    position: "absolute",
    cursor: "text",
    whiteSpace: "pre-wrap",
    padding: 2,
    border: "1px dashed transparent",
  },
  textAnnotationEditing: {
    border: "1px dashed #0f766e",
    background: "rgba(255,255,255,0.85)",
    outline: "none",
    resize: "none",
    fontFamily: "inherit",
  },
  rectAnnotation: {
    position: "absolute",
    border: "1px solid rgba(0,0,0,0.3)",
  },
  annotationRemove: {
    position: "absolute",
    top: -10,
    right: -10,
    width: 18,
    height: 18,
    borderRadius: "50%",
    background: "#ff6b6b",
    color: "#fff",
    border: "none",
    fontSize: 12,
    lineHeight: "18px",
    cursor: "pointer",
    padding: 0,
  },
  primaryButton: {
    background: "#0f766e",
    border: "none",
    borderRadius: 2,
    padding: "8px 16px",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  primaryButtonDisabled: {
    background: "#1e2b23",
    color: "#55685d",
    cursor: "not-allowed",
  },
  actionsRow: {
    display: "flex",
    gap: 8,
    marginTop: 12,
    alignItems: "center",
  },
  hint: {
    fontSize: 11,
    color: "#55685d",
    margin: "10px 0 0 0",
  },
  error: {
    fontSize: 12,
    color: "#ff6b6b",
    margin: "10px 0 0 0",
  },
  footer: {
    marginTop: 16,
    fontSize: 11,
    color: "#55685d",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
};
