import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  card: {
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
    background: "#161b22",
    border: "1px solid #30363d",
    borderRadius: 10,
    padding: 20,
    color: "#e6edf3",
    width: 440,
  },
  title: {
    margin: "0 0 16px 0",
    fontSize: 16,
    fontWeight: 700,
  },
  dropZone: {
    border: "1px dashed #30363d",
    borderRadius: 8,
    padding: "24px 16px",
    textAlign: "center",
    cursor: "pointer",
    background: "#0d1117",
  },
  dropZoneActive: {
    border: "1px dashed #58a6ff",
    background: "#0d1117",
  },
  dropZoneText: {
    fontSize: 12,
    color: "#8b949e",
    margin: 0,
  },
  toolbar: {
    display: "flex",
    gap: 6,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  toolButton: {
    background: "transparent",
    border: "1px solid #30363d",
    color: "#8b949e",
    borderRadius: 6,
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  toolButtonActive: {
    border: "1px solid #58a6ff",
    color: "#58a6ff",
    background: "rgba(88, 166, 255, 0.1)",
  },
  toolButtonDanger: {
    color: "#f85149",
  },
  pageNav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    fontSize: 12,
    color: "#8b949e",
  },
  navButton: {
    background: "#0d1117",
    border: "1px solid #30363d",
    color: "#e6edf3",
    borderRadius: 6,
    padding: "3px 10px",
    fontSize: 12,
    cursor: "pointer",
  },
  navButtonDisabled: {
    color: "#484f58",
    cursor: "not-allowed",
  },
  canvasWrap: {
    position: "relative",
    background: "#fff",
    borderRadius: 6,
    overflow: "hidden",
    margin: "0 auto",
    lineHeight: 0,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  textAnnotation: {
    position: "absolute",
    cursor: "text",
    whiteSpace: "pre-wrap",
    padding: 2,
    border: "1px dashed transparent",
  },
  textAnnotationEditing: {
    border: "1px dashed #1f6feb",
    background: "rgba(255,255,255,0.85)",
    outline: "none",
    resize: "none",
    fontFamily: "inherit",
  },
  rectAnnotation: {
    position: "absolute",
    border: "1px solid rgba(0,0,0,0.3)",
  },
  annotationRemove: {
    position: "absolute",
    top: -10,
    right: -10,
    width: 18,
    height: 18,
    borderRadius: "50%",
    background: "#f85149",
    color: "#fff",
    border: "none",
    fontSize: 12,
    lineHeight: "18px",
    cursor: "pointer",
    padding: 0,
  },
  primaryButton: {
    background: "#1f6feb",
    border: "none",
    borderRadius: 6,
    padding: "8px 16px",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  primaryButtonDisabled: {
    background: "#21262d",
    color: "#6e7681",
    cursor: "not-allowed",
  },
  actionsRow: {
    display: "flex",
    gap: 8,
    marginTop: 12,
    alignItems: "center",
  },
  hint: {
    fontSize: 11,
    color: "#6e7681",
    margin: "10px 0 0 0",
  },
  error: {
    fontSize: 12,
    color: "#f85149",
    margin: "10px 0 0 0",
  },
  footer: {
    marginTop: 16,
    fontSize: 11,
    color: "#6e7681",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
};
