import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  card: {
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
    background: "#161b22",
    border: "1px solid #30363d",
    borderRadius: 10,
    padding: 20,
    color: "#e6edf3",
    width: 460,
  },
  title: {
    margin: "0 0 16px 0",
    fontSize: 16,
    fontWeight: 700,
  },
  tabs: {
    display: "flex",
    gap: 6,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  tab: {
    background: "transparent",
    border: "1px solid #30363d",
    color: "#8b949e",
    borderRadius: 6,
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  tabActive: {
    border: "1px solid #58a6ff",
    color: "#58a6ff",
  },
  label: {
    display: "block",
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#8b949e",
    margin: "0 0 6px 0",
  },
  textarea: {
    width: "100%",
    minHeight: 110,
    resize: "vertical",
    background: "#0d1117",
    border: "1px solid #30363d",
    borderRadius: 6,
    padding: "10px 12px",
    color: "#e6edf3",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
    fontSize: 12,
    lineHeight: 1.5,
    boxSizing: "border-box",
  },
  textareaError: {
    border: "1px solid #f85149",
  },
  input: {
    background: "#0d1117",
    border: "1px solid #30363d",
    borderRadius: 6,
    padding: "7px 10px",
    color: "#e6edf3",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
    fontSize: 12,
    boxSizing: "border-box",
  },
  select: {
    background: "#0d1117",
    border: "1px solid #30363d",
    borderRadius: 6,
    padding: "6px 8px",
    color: "#e6edf3",
    fontSize: 12,
  },
  row: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
    margin: "10px 0",
  },
  field: {
    marginBottom: 14,
  },
  primaryButton: {
    background: "#1f6feb",
    border: "none",
    borderRadius: 6,
    padding: "7px 14px",
    color: "#fff",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  secondaryButton: {
    background: "transparent",
    border: "1px solid #30363d",
    borderRadius: 6,
    padding: "6px 12px",
    color: "#8b949e",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  checkboxLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    color: "#8b949e",
    cursor: "pointer",
  },
  hint: {
    fontSize: 11,
    color: "#6e7681",
    margin: "10px 0 0 0",
  },
  error: {
    fontSize: 12,
    color: "#f85149",
    margin: "8px 0 0 0",
  },
  success: {
    fontSize: 12,
    color: "#3fb950",
    margin: "8px 0 0 0",
  },
  matchList: {
    listStyle: "none",
    margin: "10px 0 0 0",
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    maxHeight: 160,
    overflowY: "auto",
  },
  matchItem: {
    background: "#0d1117",
    border: "1px solid #21262d",
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: 12,
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
  highlightMark: {
    background: "rgba(88, 166, 255, 0.35)",
    color: "#e6edf3",
    borderRadius: 2,
  },
  footer: {
    marginTop: 16,
    fontSize: 11,
    color: "#6e7681",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
};
