import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  card: {
    fontFamily:
      "'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    background: "#0f1512",
    border: "1px solid #2c3d33",
    borderRadius: 3,
    padding: 20,
    color: "#e7f2ec",
    width: 460,
  },
  title: {
    margin: "0 0 16px 0",
    fontSize: 16,
    fontWeight: 700,
  },
  tabs: {
    display: "flex",
    gap: 6,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  tab: {
    background: "transparent",
    border: "1px solid #2c3d33",
    color: "#839a8d",
    borderRadius: 2,
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  tabActive: {
    border: "1px solid #2dd4bf",
    color: "#2dd4bf",
  },
  label: {
    display: "block",
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#839a8d",
    margin: "0 0 6px 0",
  },
  textarea: {
    width: "100%",
    minHeight: 110,
    resize: "vertical",
    background: "#080b09",
    border: "1px solid #2c3d33",
    borderRadius: 2,
    padding: "10px 12px",
    color: "#e7f2ec",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
    fontSize: 12,
    lineHeight: 1.5,
    boxSizing: "border-box",
  },
  textareaError: {
    border: "1px solid #ff6b6b",
  },
  input: {
    background: "#080b09",
    border: "1px solid #2c3d33",
    borderRadius: 2,
    padding: "7px 10px",
    color: "#e7f2ec",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
    fontSize: 12,
    boxSizing: "border-box",
  },
  select: {
    background: "#080b09",
    border: "1px solid #2c3d33",
    borderRadius: 2,
    padding: "6px 8px",
    color: "#e7f2ec",
    fontSize: 12,
  },
  row: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
    margin: "10px 0",
  },
  field: {
    marginBottom: 14,
  },
  primaryButton: {
    background: "#0f766e",
    border: "none",
    borderRadius: 2,
    padding: "7px 14px",
    color: "#fff",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  secondaryButton: {
    background: "transparent",
    border: "1px solid #2c3d33",
    borderRadius: 2,
    padding: "6px 12px",
    color: "#839a8d",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  checkboxLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    color: "#839a8d",
    cursor: "pointer",
  },
  hint: {
    fontSize: 11,
    color: "#55685d",
    margin: "10px 0 0 0",
  },
  error: {
    fontSize: 12,
    color: "#ff6b6b",
    margin: "8px 0 0 0",
  },
  success: {
    fontSize: 12,
    color: "#3fb950",
    margin: "8px 0 0 0",
  },
  matchList: {
    listStyle: "none",
    margin: "10px 0 0 0",
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    maxHeight: 160,
    overflowY: "auto",
  },
  matchItem: {
    background: "#080b09",
    border: "1px solid #1e2b23",
    borderRadius: 2,
    padding: "6px 10px",
    fontSize: 12,
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
  highlightMark: {
    background: "rgba(45, 212, 191, 0.35)",
    color: "#e7f2ec",
    borderRadius: 2,
  },
  footer: {
    marginTop: 16,
    fontSize: 11,
    color: "#55685d",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
};
