import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  card: {
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
    background: "#161b22",
    border: "1px solid #30363d",
    borderRadius: 10,
    padding: 20,
    color: "#e6edf3",
    width: 680,
  },
  title: {
    margin: "0 0 16px 0",
    fontSize: 16,
    fontWeight: 700,
  },
  dropZone: {
    border: "1px dashed #30363d",
    borderRadius: 8,
    padding: "24px 16px",
    textAlign: "center",
    cursor: "pointer",
    background: "#0d1117",
  },
  dropZoneActive: {
    border: "1px dashed #58a6ff",
    background: "#0d1117",
  },
  dropZoneText: {
    fontSize: 12,
    color: "#8b949e",
    margin: 0,
  },
  layout: {
    display: "flex",
    gap: 20,
    alignItems: "flex-start",
  },
  previewColumn: {
    flexShrink: 0,
    width: 280,
  },
  previewNav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    fontSize: 12,
    color: "#8b949e",
  },
  navButton: {
    background: "#0d1117",
    border: "1px solid #30363d",
    color: "#e6edf3",
    borderRadius: 6,
    padding: "3px 10px",
    fontSize: 12,
    cursor: "pointer",
  },
  navButtonDisabled: {
    color: "#484f58",
    cursor: "not-allowed",
  },
  canvasWrap: {
    background: "#fff",
    borderRadius: 6,
    overflow: "hidden",
    lineHeight: 0,
  },
  fieldsColumn: {
    flex: 1,
    minWidth: 0,
    maxHeight: 480,
    overflowY: "auto",
    paddingRight: 4,
  },
  fieldGroup: {
    marginBottom: 16,
  },
  fieldLabel: {
    display: "block",
    fontSize: 11,
    fontWeight: 700,
    color: "#8b949e",
    marginBottom: 6,
    wordBreak: "break-word",
  },
  textInput: {
    width: "100%",
    background: "#0d1117",
    border: "1px solid #30363d",
    borderRadius: 6,
    padding: "8px 10px",
    color: "#e6edf3",
    fontSize: 13,
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    background: "#0d1117",
    border: "1px solid #30363d",
    borderRadius: 6,
    padding: "8px 10px",
    color: "#e6edf3",
    fontSize: 13,
    boxSizing: "border-box",
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  radioOption: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    color: "#e6edf3",
    marginBottom: 4,
  },
  unsupportedField: {
    fontSize: 12,
    color: "#6e7681",
    fontStyle: "italic",
  },
  primaryButton: {
    background: "#1f6feb",
    border: "none",
    borderRadius: 6,
    padding: "8px 16px",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  primaryButtonDisabled: {
    background: "#21262d",
    color: "#6e7681",
    cursor: "not-allowed",
  },
  secondaryButton: {
    background: "transparent",
    border: "1px solid #30363d",
    borderRadius: 6,
    padding: "7px 14px",
    color: "#8b949e",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  actionsRow: {
    display: "flex",
    gap: 8,
    marginTop: 16,
    alignItems: "center",
  },
  hint: {
    fontSize: 11,
    color: "#6e7681",
    margin: "10px 0 0 0",
  },
  error: {
    fontSize: 12,
    color: "#f85149",
    margin: "10px 0 0 0",
  },
  footer: {
    marginTop: 16,
    fontSize: 11,
    color: "#6e7681",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
};
