import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  card: {
    fontFamily:
      "'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    background: "#0f1512",
    border: "1px solid #2c3d33",
    borderRadius: 3,
    padding: 20,
    color: "#e7f2ec",
    width: 680,
  },
  title: {
    margin: "0 0 16px 0",
    fontSize: 16,
    fontWeight: 700,
  },
  dropZone: {
    border: "1px dashed #2c3d33",
    borderRadius: 2,
    padding: "24px 16px",
    textAlign: "center",
    cursor: "pointer",
    background: "#080b09",
  },
  dropZoneActive: {
    border: "1px dashed #2dd4bf",
    background: "#080b09",
  },
  dropZoneText: {
    fontSize: 12,
    color: "#839a8d",
    margin: 0,
  },
  layout: {
    display: "flex",
    gap: 20,
    alignItems: "flex-start",
  },
  previewColumn: {
    flexShrink: 0,
    width: 280,
  },
  previewNav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    fontSize: 12,
    color: "#839a8d",
  },
  navButton: {
    background: "#080b09",
    border: "1px solid #2c3d33",
    color: "#e7f2ec",
    borderRadius: 2,
    padding: "3px 10px",
    fontSize: 12,
    cursor: "pointer",
  },
  navButtonDisabled: {
    color: "#484f58",
    cursor: "not-allowed",
  },
  canvasWrap: {
    background: "#fff",
    borderRadius: 2,
    overflow: "hidden",
    lineHeight: 0,
  },
  fieldsColumn: {
    flex: 1,
    minWidth: 0,
    maxHeight: 480,
    overflowY: "auto",
    paddingRight: 4,
  },
  fieldGroup: {
    marginBottom: 16,
  },
  fieldLabel: {
    display: "block",
    fontSize: 11,
    fontWeight: 700,
    color: "#839a8d",
    marginBottom: 6,
    wordBreak: "break-word",
  },
  textInput: {
    width: "100%",
    background: "#080b09",
    border: "1px solid #2c3d33",
    borderRadius: 2,
    padding: "8px 10px",
    color: "#e7f2ec",
    fontSize: 13,
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    background: "#080b09",
    border: "1px solid #2c3d33",
    borderRadius: 2,
    padding: "8px 10px",
    color: "#e7f2ec",
    fontSize: 13,
    boxSizing: "border-box",
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  radioOption: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    color: "#e7f2ec",
    marginBottom: 4,
  },
  unsupportedField: {
    fontSize: 12,
    color: "#55685d",
    fontStyle: "italic",
  },
  primaryButton: {
    background: "#0f766e",
    border: "none",
    borderRadius: 2,
    padding: "8px 16px",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  primaryButtonDisabled: {
    background: "#1e2b23",
    color: "#55685d",
    cursor: "not-allowed",
  },
  secondaryButton: {
    background: "transparent",
    border: "1px solid #2c3d33",
    borderRadius: 2,
    padding: "7px 14px",
    color: "#839a8d",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  actionsRow: {
    display: "flex",
    gap: 8,
    marginTop: 16,
    alignItems: "center",
  },
  hint: {
    fontSize: 11,
    color: "#55685d",
    margin: "10px 0 0 0",
  },
  error: {
    fontSize: 12,
    color: "#ff6b6b",
    margin: "10px 0 0 0",
  },
  footer: {
    marginTop: 16,
    fontSize: 11,
    color: "#55685d",
    fontFamily: "'JetBrains Mono', ui-monospace, monospace",
  },
};
